### ISSUE TITLE
a99SB-disp for AMBER

### ISSUE THREAD

**Issue by mohamedmarzouk2020** [DEShawResearch/viparr-ffpublic#1]
Is there  any parameter file for this force filed compatible with AMBER? 
I want to simulate system with some IDRs so I want to test this force filed at first.

**Comment by fennm** [comment]
@mohamedmarzouk2020, in lieu of pull requests or issues, please direct questions to
desmond@DEShawResearch.com

**Comment by mohamedmarzouk2020** [comment]
Ok, Thank you
