### ISSUE TITLE
multiple force field parameters assignment 

### ISSUE THREAD

**Issue by yiannisgaldadas** [DEShawResearch/viparr-ffpublic#2]
I have a protein/membrane system, which I’m trying to simulate, but viparr gives me a segmentation fault: 11 error whenever I try to assign the ff parameters to it. 

I passed separately each component of the system through vippar to see which one might be causing the problem, but they all seem to be fine (viparr assigns the parameters without any error). The segmentation fault occurs either when I pass more than one ffs in each component of the system, or when I pass multiple ffs in the system, i.e. 

viparr protein.mae out.dms  -f aa.amber.ff99SBstar-ILDN (FAILS)
viparr membrane_fixed.mae out.dms   -f lipid.charmm.c36 (WORKS)
viparr membrane_fixed.mae out.dms  -f lipid.charmm.c36 -f aa.amber.ff99SBstar-ILDN (FAILS)
viparr system.mae out.dms  -f lipid.charmm.c36 -f aa.amber.ff99SBstar-ILDN -f water.tip3p (FAILS)

Do you happen to have any idea as to what may be causing the problem? Any suggestion that I could explore to debug the problem would be really helpful. 

Best,
Yiannis

**Comment by fennm** [comment]
@yiannisgaldadas In lieu of pull requests or issues, please direct questions to
desmond@DEShawResearch.com
